shop/urls.py
from django.urls import path
from .views import catView,product, productView

urlpatterns = [
    path('',productView.as_view(),name='home'),
    path('catergory/',catView.as_view(),name='catergory'),
    
]

store/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
    #path('member/', include('django.contrib.auth.urls')),
    #path('member/', include('customer_user.urls')),


]+ static(settings.MEDIA_URL,document_root =settings.MEDIA_ROOT)

shop/models.py
from django.db import models

# Create your models here.



class catergory(models.Model):
    cat_name = models.CharField(max_length=50)
    cat_image = models.ImageField(null=True,blank=True,upload_to= 'images/')

    def __str__(self):
        return self.cat_name
    
class product(models.Model):
    product_name = models.CharField(max_length=100)
    product_price =models.PositiveIntegerField(default=45000)
    product_cat = models.ForeignKey(catergory,on_delete=models.CASCADE)
    product_image = models.ImageField(null=True,blank=True,upload_to='images/')
    product_dis =models.TextField(default='product')

    def __str__(self):
        return self.product_name
    

shop/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from.models import *

# Create your views here.

class catView(TemplateView):
    template_name = 'catergory.html'

    def get_context_data(self, **kwargs):
        contex= super().get_context_data(**kwargs)
        contex['my_name']='isuru'
        contex['catergory']=catergory.objects.all()
        return contex


class productView(TemplateView):
    template_name='product.html'

    def get_context_data(self, **kwargs):
        contex= super().get_context_data(**kwargs)
        contex['product']=product.objects.all()
        return contex
    

shop/templates/base.html
<!doctype html>

<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <style>
      .lin{
        text-decoration: none;

      }
      .text{
        font-family: Cambria;

      }

    </style>
    <title>ecom</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'catergory' %}">catergory</a>
        </li>
        
        
      </ul>
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="">Logout</a></li>
            <li><a class="dropdown-item" href="#">Login</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Rgister</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

    {% block body %}
    
    
    
    {% endblock body %}

    <footer class="footer mt-5 py-3 bg-success">
      <div class="container">
        <span class="text-danger text-bg-dark">All right recieved...</span>
      </div>
    </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

shop/templates/catergory.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12 mt-3">
				<img src="{% static 'images/banner-bg.jpg' %}" alt="Item 1" width="100%">


			</div>
			{% for cat in catergory %}

	<h2 class="text-center mt-2 shadow p-3 bg-secondary">{{cat.cat_name}}</h2>
	<hr>
	<div class ="row mt-3">

		{% for x in cat.product_set.all %}
		
		
		<div class ="col-md-4 mt-3">

			<div class="card shadow" style="width: 18rem;" >
				<img src="{{x.product_image.url}}" class="card-img-top" alt="..."width="250" height="250">
				<div class="card-body">
				  <h5 class="card-title"><a class="lin" href="">{{x.product_name}}</a></h5>
				  
				  <a href="#" class="btn btn-outline-danger "><img src="{% static 'images/cart.png' %}" alt="" width="30" height="30"></a>
				</div>
			  </div>
			 
		  
			
			
		  </div>
		
		{% endfor %}
		</div>
{% endfor %}

</div>
</div>

{% endblock  %}

shop/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12 mt-3">
				<img src="{% static 'images/banner-bg.jpg' %}" alt="Item 1" width="100%">


			</div>
			{% for cat in catergory %}

	<h2 class="text-center mt-2 shadow p-3">{{cat.cat_name}}</h2>
	<hr>
	<div class ="row mt-3">

		{% for x in cat.product_set.all %}
		
		
		<div class ="col-md-4 mt-3">

			<div class="card shadow" style="width: 18rem;" >
				<img src="{{x.product_image.url}}" class="card-img-top" alt="..."width="250" height="250">
				<div class="card-body">
				  <h5 class="card-title"><a class="lin" href="">{{x.product_name}}</a></h5>
				  
				  <a href="#" class="btn btn-outline-danger "><img src="{% static 'images/cart.png' %}" alt="" width="30" height="30"></a>
				</div>
			  </div>
			 
		  
			
			
		  </div>
		
		{% endfor %}
		</div>
{% endfor %}

</div>
</div>

{% endblock  %}

shop/templates/product.html
{% extends 'base.html' %}

{% load static %}


{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-12 mt-3">
				<img src="{% static 'images/banner-bg.jpg' %}" alt="Item 1" width="100%">


			</div>
			

	<h2 class="text-center shadow p-3 m-3 bg-secondary">Products</h2>
	<hr>
	<div class ="row mt-5">

		{% for x in product %}
		
		
		<div class ="col-md-4 mt-3">

			<div class="card shadow" style="width: 18rem;" >
				<img src="{{x.product_image.url}}" class="card-img-top" alt="..."width="250" height="250">
				<div class="card-body">
				  <h5 class="card-title"><a class="lin" href="">{{x.product_name}}</a></h5>
				  
				  <a href="#" class="btn btn-outline-danger "><img src="{% static 'images/cart.png' %}" alt="" width="30" height="30"></a>
				</div>
			  </div>
			 
		  
			
			
		  </div>
		
		{% endfor %}
		</div>


</div>
</div>

{% endblock  %}